# Image URL to use all building/pushing image targets
IMG ?= controller:latest

CHART_DIR ?= helm-templates/ratelimit

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# CONTAINER_TOOL defines the container tool to be used for building images.
CONTAINER_TOOL ?= docker

# Setting SHELL to bash allows bash commands to be executed by recipes.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec

.PHONY: all
all: build

##@ General

.PHONY: help
help: ## Display this help.
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_0-9-]+:.*?##/ { printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

##@ Development

.PHONY: manifests
manifests: controller-gen ## Generate RBAC and CustomResourceDefinition objects.
	"$(CONTROLLER_GEN)" rbac:roleName=manager-role paths="./cmd;./internal/..." output:artifacts:config=config/rbac
	"$(CONTROLLER_GEN)" crd paths="./api/v1alpha1/..." output:crd:artifacts:config=config/crd/bases

.PHONY: generate
generate: controller-gen ## Generate code containing DeepCopy, DeepCopyInto, and DeepCopyObject method implementations.
	"$(CONTROLLER_GEN)" object:headerFile="hack/boilerplate.go.txt" paths="./..."

# The chart ships its own copy of the CRD, so the template is derived — never edit
# $(CHART_DIR)/templates/crd-*.yaml by hand. Depends on manifests so the copy can
# never be made from a stale config/crd/bases.
#
# The CRD is the one cluster-scoped object in a namespace-scoped install: several
# per-namespace releases share the single ratelimitpolicies.ratelimit.netcracker.com
# object, so the template carries helm.sh/resource-policy: keep to stop the first
# uninstall from taking the CRD (and every other namespace's policies) with it.
.PHONY: sync-helm-crds
sync-helm-crds: manifests ## Regenerate the Helm CRD templates from config/crd/bases.
	@rm -f $(CHART_DIR)/templates/crd-*.yaml
	@for f in config/crd/bases/*.yaml; do \
		kind=$$(basename "$$f" .yaml | sed 's/^ratelimit\.netcracker\.com_//'); \
		out="$(CHART_DIR)/templates/crd-$$kind.yaml"; \
		{ \
			echo '# Generated by "make sync-helm-crds" from config/crd/bases. DO NOT EDIT.'; \
			awk 'NR==1 && $$0 == "---" { next } \
			     /^  annotations:$$/ && !done { print; \
			       print "    # The CRD is cluster-scoped and shared by every namespace"; \
			       print "    # installation, so uninstalling one release must not remove it."; \
			       print "    helm.sh/resource-policy: keep"; done=1; next } \
			     { print }' "$$f"; \
		} > "$$out"; \
		grep -q 'helm.sh/resource-policy: keep' "$$out" || \
			{ echo "ERROR: $$out has no resource-policy annotation; the generated CRD lost its annotations block" >&2; exit 1; }; \
	done
	@echo "Synced $$(ls config/crd/bases/*.yaml | wc -l | tr -d ' ') Helm CRD template(s)"

# Alias for the name used in the task description
.PHONY: helm-crd
helm-crd: sync-helm-crds ## Alias for sync-helm-crds.

.PHONY: fmt
fmt: ## Run go fmt against code, the engine module included.
	go fmt ./...
	cd engine && go fmt ./...

.PHONY: vet
vet: ## Run go vet against code, the engine module included.
	go vet ./...
	cd engine && go vet ./...

# TEST_PKGS lists only packages that contain test files. Passing packages without
# test files to "go test -coverprofile" makes Go invoke "covdata" to merge empty
# coverage shards, which fails on some filesystems and contributes no coverage
# anyway.
TEST_PKGS = $(shell go list -f '{{if or .TestGoFiles .XTestGoFiles}}{{.ImportPath}}{{end}}' ./...)

.PHONY: test-engine
test-engine: ## Run the engine module tests. Its own go.mod hides it from ./... of the root module.
	cd engine && go vet ./... && go test -race ./...

.PHONY: test-unit
test-unit: fmt vet test-engine ## Run unit tests only — no envtest, no cluster, no network.
	go test $(filter-out %/internal/controller,$(TEST_PKGS)) -coverprofile cover-unit.out

.PHONY: test
test: manifests generate fmt vet test-engine setup-envtest ## Run all tests, including the envtest controller suite. Needs internet on the first run to fetch the envtest binaries.
	@echo "Running tests with KUBEBUILDER_ASSETS=$$("$(ENVTEST)" use $(ENVTEST_K8S_VERSION) --bin-dir "$(LOCALBIN)" -p path)"
	KUBEBUILDER_ASSETS="$(shell "$(ENVTEST)" use $(ENVTEST_K8S_VERSION) --bin-dir "$(LOCALBIN)" -p path)" go test $(TEST_PKGS) -coverprofile cover.out

# The e2e suite drives real traffic through the gateways, so it needs a cluster
# with Istio ambient, the gateways, and this chart already installed. It changes
# no release: install first, then run.
.PHONY: test-e2e
test-e2e: ## Run the bash end-to-end suites against an installed release.
	NAMESPACE="$(E2E_NAMESPACE)" bash tests/e2e/test-suite.sh '$(E2E_TEST)'

# The Go end-to-end suites (tests/e2e-go), replacing the bash ones suite by
# suite. Same contract: the cluster already has Istio, the gateways, and the
# chart installed; the suite installs nothing. The JUnit report is the Go
# analog of a surefire report - CI uploads it as an artifact.
.PHONY: test-e2e-go
test-e2e-go: ginkgo ## Run the Go end-to-end suites against an installed release.
	@mkdir -p "$(E2E_ARTIFACTS)"
	NAMESPACE="$(E2E_NAMESPACE)" "$(GINKGO)" -tags e2e -v \
	  --flake-attempts=2 --poll-progress-after=120s \
	  --junit-report=e2e-go.xml --output-dir="$(E2E_ARTIFACTS)" \
	  ./tests/e2e-go

E2E_ARTIFACTS ?= artifacts

E2E_NAMESPACE ?= core
E2E_TEST ?= *

.PHONY: lint
lint: golangci-lint ## Run golangci-lint linter, the engine module included.
	"$(GOLANGCI_LINT)" run
	cd engine && "$(GOLANGCI_LINT)" run

.PHONY: lint-fix
lint-fix: golangci-lint ## Run golangci-lint linter and perform fixes, the engine module included.
	"$(GOLANGCI_LINT)" run --fix
	cd engine && "$(GOLANGCI_LINT)" run --fix

# Linted once per resource profile, because the chart is never installed without
# one: the profile supplies REPLICAS and the resource requests and limits, and
# values.schema.json requires them. Linting values.yaml alone would fail, and a
# schema loose enough to pass would let a missing profile through to a
# Deployment with empty resources.
.PHONY: helm-lint
helm-lint: ## Lint the Helm chart against every resource profile.
	@for profile in $(CHART_DIR)/resource-profiles/*.yaml; do \
		echo "--- lint with $$(basename "$$profile")"; \
		helm lint $(CHART_DIR) -f "$$profile" || exit 1; \
	done

##@ Build

.PHONY: build
build: manifests generate fmt vet ## Build manager binary.
	go build -o bin/manager ./cmd/

.PHONY: run
run: manifests generate fmt vet ## Run the service from your host.
	go run ./cmd/

.PHONY: docker-build
docker-build: ## Build docker image with the manager.
	$(CONTAINER_TOOL) build -t ${IMG} .

.PHONY: docker-push
docker-push: ## Push docker image with the manager.
	$(CONTAINER_TOOL) push ${IMG}

PLATFORMS ?= linux/arm64,linux/amd64
.PHONY: docker-buildx
docker-buildx: ## Build and push docker image for the manager for cross-platform support.
	sed -e '1 s/\(^FROM\)/FROM --platform=\$$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=\$$\{BUILDPLATFORM\}/' Dockerfile > Dockerfile.cross
	- $(CONTAINER_TOOL) buildx create --name ratelimit-builder
	$(CONTAINER_TOOL) buildx use ratelimit-builder
	- $(CONTAINER_TOOL) buildx build --push --platform=$(PLATFORMS) --tag ${IMG} -f Dockerfile.cross .
	- $(CONTAINER_TOOL) buildx rm ratelimit-builder
	rm Dockerfile.cross

##@ Deployment

ifndef ignore-not-found
  ignore-not-found = false
endif

.PHONY: install
install: manifests ## Install CRDs into the K8s cluster specified in ~/.kube/config.
	"$(KUBECTL)" apply -f config/crd/bases

.PHONY: uninstall
uninstall: manifests ## Uninstall CRDs from the K8s cluster specified in ~/.kube/config.
	"$(KUBECTL)" delete --ignore-not-found=$(ignore-not-found) -f config/crd/bases

##@ Dependencies

## Location to install dependencies to
LOCALBIN ?= $(shell pwd)/bin
$(LOCALBIN):
	mkdir -p "$(LOCALBIN)"

## Tool Binaries
KUBECTL ?= kubectl
CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen
ENVTEST ?= $(LOCALBIN)/setup-envtest
GOLANGCI_LINT = $(LOCALBIN)/golangci-lint
GINKGO = $(LOCALBIN)/ginkgo

## Tool Versions
CONTROLLER_TOOLS_VERSION ?= v0.21.0
GOLANGCI_LINT_VERSION ?= v2.8.0

# The ginkgo CLI version follows go.mod, so the runner and the library cannot
# drift apart.
GINKGO_VERSION ?= $(call gomodver,github.com/onsi/ginkgo/v2)

# Both versions are derived from go.mod so that the envtest control plane cannot
# drift from the client libraries the service is built against.
# ENVTEST_VERSION is the controller-runtime release branch, e.g. release-0.24.
ENVTEST_VERSION ?= $(shell v='$(call gomodver,sigs.k8s.io/controller-runtime)'; \
  [ -n "$$v" ] || { echo "Set ENVTEST_VERSION manually (controller-runtime replace has no tag)" >&2; exit 1; }; \
  printf '%s\n' "$$v" | sed -E 's/^v?([0-9]+)\.([0-9]+).*/release-\1.\2/')

# ENVTEST_K8S_VERSION is the Kubernetes version of the envtest binaries, e.g. 1.36.
ENVTEST_K8S_VERSION ?= $(shell v='$(call gomodver,k8s.io/api)'; \
  [ -n "$$v" ] || { echo "Set ENVTEST_K8S_VERSION manually (k8s.io/api replace has no tag)" >&2; exit 1; }; \
  printf '%s\n' "$$v" | sed -E 's/^v?[0-9]+\.([0-9]+).*/1.\1/')

.PHONY: controller-gen
controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary.
$(CONTROLLER_GEN): $(LOCALBIN)
	$(call go-install-tool,$(CONTROLLER_GEN),sigs.k8s.io/controller-tools/cmd/controller-gen,$(CONTROLLER_TOOLS_VERSION))

.PHONY: setup-envtest
setup-envtest: envtest ## Download the binaries the envtest suite needs into bin/.
	@echo "Setting up envtest binaries for Kubernetes version $(ENVTEST_K8S_VERSION)..."
	@"$(ENVTEST)" use $(ENVTEST_K8S_VERSION) --bin-dir "$(LOCALBIN)" -p path || { \
		echo "Error: Failed to set up envtest binaries for version $(ENVTEST_K8S_VERSION)."; \
		exit 1; \
	}

.PHONY: envtest
envtest: $(ENVTEST) ## Download setup-envtest locally if necessary.
$(ENVTEST): $(LOCALBIN)
	$(call go-install-tool,$(ENVTEST),sigs.k8s.io/controller-runtime/tools/setup-envtest,$(ENVTEST_VERSION))

.PHONY: golangci-lint
golangci-lint: $(GOLANGCI_LINT) ## Download golangci-lint locally if necessary.
$(GOLANGCI_LINT): $(LOCALBIN)
	$(call go-install-tool,$(GOLANGCI_LINT),github.com/golangci/golangci-lint/v2/cmd/golangci-lint,$(GOLANGCI_LINT_VERSION))

.PHONY: ginkgo
ginkgo: $(GINKGO) ## Download the ginkgo CLI locally if necessary.
$(GINKGO): $(LOCALBIN)
	$(call go-install-tool,$(GINKGO),github.com/onsi/ginkgo/v2/ginkgo,$(GINKGO_VERSION))

# go-install-tool will 'go install' any package with custom target and name of binary, if it doesn't exist
# $1 - target path with name of binary
# $2 - package url which can be installed
# $3 - specific version of package
define go-install-tool
@[ -f "$(1)-$(3)" ] && [ "$$(readlink -- "$(1)" 2>/dev/null)" = "$(1)-$(3)" ] || { \
set -e; \
package=$(2)@$(3) ;\
echo "Downloading $${package}" ;\
rm -f "$(1)" ;\
GOBIN="$(LOCALBIN)" go install $${package} ;\
mv "$(LOCALBIN)/$$(basename "$(1)")" "$(1)-$(3)" ;\
} ;\
ln -sf "$(1)-$(3)" "$(1)"
endef

define gomodver
$(shell go list -m -f '{{if .Replace}}{{.Replace.Version}}{{else}}{{.Version}}{{end}}' $(1) 2>/dev/null)
endef
