{{- if ne (include "ratelimit.mode" .) "satellite" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratelimit.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ratelimit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      appProtocol: grpc
      port: {{ .Values.rls.port }}
      targetPort: grpc
      protocol: TCP
    {{- if .Values.management.enabled }}
    - name: management
      appProtocol: http
      port: {{ .Values.management.port }}
      targetPort: management
      protocol: TCP
    {{- end }}
  selector:
    {{- include "ratelimit.selectorLabels" . | nindent 4 }}
{{- end }}
