apiVersion: v2
appVersion: "0.1.0"
description: Rate limit service and Envoy rate limit service for Istio ambient gateways
name: ratelimit
type: application
# The effective version is computed during Helm generation
version: 0.0.1
