resources:
  - ratelimit_v1alpha1_ratelimitmapping.yaml
  - ratelimit_v1alpha1_ratelimitpolicy_public.yaml
  - ratelimit_v1alpha1_ratelimitpolicy_private.yaml
  - ratelimit_v1alpha1_ratelimitpolicy_quote_api.yaml
