{{- if ne (include "ratelimit.mode" .) "satellite" }}
{{- if .Values.MONITORING_ENABLED }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: '{{ .Values.SERVICE_NAME }}-pod-monitor'
  namespace: '{{ .Values.NAMESPACE }}'
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID }}'
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/processed-by-operator: victoriametrics-operator
spec:
  podMetricsEndpoints:
    - interval: 30s
      port: metrics
      scheme: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - '{{ .Values.NAMESPACE }}'
  selector:
    matchLabels:
      name: '{{ .Values.SERVICE_NAME }}'
{{- end }}
{{- end }}
