{{- if ne (include "ratelimit.mode" .) "satellite" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Values.SERVICE_NAME }}'
  namespace: '{{ .Values.NAMESPACE | default .Release.Namespace }}'
  labels:
    app.kubernetes.io/name: '{{ .Values.SERVICE_NAME }}'
    app.kubernetes.io/part-of: '{{ .Values.APPLICATION_NAME }}'
    app.kubernetes.io/managed-by: '{{ .Values.MANAGED_BY }}'
    deployment.netcracker.com/sessionId: '{{ .Values.DEPLOYMENT_SESSION_ID | default "unimplemented" }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ .Values.SERVICE_NAME }}'
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.serviceAccount.name | default .Values.SERVICE_NAME }}'
    namespace: '{{ .Values.NAMESPACE | default .Release.Namespace }}'
{{- end }}
