apiVersion: v1
kind: Service
metadata:
  name: {{ include "ratelimit-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ratelimit-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      appProtocol: grpc
      port: {{ .Values.rls.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "ratelimit-operator.selectorLabels" . | nindent 4 }}
