CPU_REQUEST: "50m"
MEMORY_REQUEST: "128Mi"
CPU_LIMIT: "1"
MEMORY_LIMIT: "256Mi"
REPLICAS: 2
HPA_ENABLED: true
HPA_AVG_CPU_UTILIZATION_TARGET_PERCENT: 75
HPA_SCALING_UP_STABILIZATION_WINDOW_SECONDS: 60
HPA_SCALING_UP_PODS_PERIOD_SECONDS: 60
HPA_SCALING_UP_PODS_VALUE: 1
HPA_SCALING_DOWN_STABILIZATION_WINDOW_SECONDS: 300
HPA_SCALING_DOWN_PODS_PERIOD_SECONDS: 60
HPA_SCALING_DOWN_PODS_VALUE: 1
HPA_MIN_REPLICAS: 2
HPA_MAX_REPLICAS: 5
